// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/proto/message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UuidV4               string               `protobuf:"bytes,2,opt,name=uuid_v4,json=uuidV4,proto3" json:"uuid_v4,omitempty"`
	AppId                string               `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Topic                string               `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Publishes            []*PublishResponse   `protobuf:"bytes,6,rep,name=publishes,proto3" json:"publishes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetUuidV4() string {
	if m != nil {
		return m.UuidV4
	}
	return ""
}

func (m *Message) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Message) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Message) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Message) GetPublishes() []*PublishResponse {
	if m != nil {
		return m.Publishes
	}
	return nil
}

type PublishResponse struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgId                int64                `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{1}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PublishResponse) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *PublishResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type CreateRequest struct {
	UuidV4               string   `protobuf:"bytes,1,opt,name=uuid_v4,json=uuidV4,proto3" json:"uuid_v4,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Emit                 bool     `protobuf:"varint,5,opt,name=emit,proto3" json:"emit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUuidV4() string {
	if m != nil {
		return m.UuidV4
	}
	return ""
}

func (m *CreateRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *CreateRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateRequest) GetEmit() bool {
	if m != nil {
		return m.Emit
	}
	return false
}

type FindRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UuidV4               string   `protobuf:"bytes,2,opt,name=uuid_v4,json=uuidV4,proto3" json:"uuid_v4,omitempty"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Topic                string   `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	CreatedFrom          string   `protobuf:"bytes,5,opt,name=created_from,json=createdFrom,proto3" json:"created_from,omitempty"`
	CreatedTo            string   `protobuf:"bytes,6,opt,name=created_to,json=createdTo,proto3" json:"created_to,omitempty"`
	Limit                int64    `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string   `protobuf:"bytes,9,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{3}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FindRequest) GetUuidV4() string {
	if m != nil {
		return m.UuidV4
	}
	return ""
}

func (m *FindRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FindRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *FindRequest) GetCreatedFrom() string {
	if m != nil {
		return m.CreatedFrom
	}
	return ""
}

func (m *FindRequest) GetCreatedTo() string {
	if m != nil {
		return m.CreatedTo
	}
	return ""
}

func (m *FindRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type ListResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PublishMessageRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishMessageRequest) Reset()         { *m = PublishMessageRequest{} }
func (m *PublishMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PublishMessageRequest) ProtoMessage()    {}
func (*PublishMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42f305e3585c9494, []int{8}
}

func (m *PublishMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMessageRequest.Unmarshal(m, b)
}
func (m *PublishMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMessageRequest.Marshal(b, m, deterministic)
}
func (m *PublishMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMessageRequest.Merge(m, src)
}
func (m *PublishMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PublishMessageRequest.Size(m)
}
func (m *PublishMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMessageRequest proto.InternalMessageInfo

func (m *PublishMessageRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*PublishResponse)(nil), "message.PublishResponse")
	proto.RegisterType((*CreateRequest)(nil), "message.CreateRequest")
	proto.RegisterType((*FindRequest)(nil), "message.FindRequest")
	proto.RegisterType((*ListResponse)(nil), "message.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "message.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "message.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "message.DeleteResponse")
	proto.RegisterType((*PublishMessageRequest)(nil), "message.PublishMessageRequest")
}

func init() { proto.RegisterFile("message/proto/message.proto", fileDescriptor_42f305e3585c9494) }

var fileDescriptor_42f305e3585c9494 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0xda, 0x35, 0x6d, 0x4e, 0xb7, 0x32, 0xcc, 0xda, 0x99, 0x30, 0x46, 0xf1, 0x0d, 0xd5,
	0x84, 0x1a, 0x69, 0x4c, 0x88, 0xbf, 0x1b, 0x7e, 0x34, 0x34, 0xc1, 0x04, 0x0a, 0x13, 0xe2, 0xae,
	0x4a, 0x1b, 0x37, 0x33, 0x6a, 0xea, 0x10, 0x3b, 0x93, 0x26, 0xb4, 0x1b, 0x5e, 0x81, 0x47, 0xe2,
	0x0d, 0xe0, 0x15, 0xb8, 0xe6, 0x19, 0x50, 0x1d, 0x3b, 0xe9, 0xcf, 0x26, 0xae, 0xb8, 0xf3, 0x39,
	0xf9, 0xfc, 0xf9, 0x9c, 0xef, 0x3b, 0x39, 0x70, 0x2b, 0xa6, 0x42, 0x04, 0x11, 0xf5, 0x92, 0x94,
	0x4b, 0xee, 0xe9, 0xa8, 0xaf, 0x22, 0x54, 0xd7, 0xa1, 0xbb, 0x13, 0x71, 0x1e, 0x4d, 0xa8, 0x17,
	0x24, 0xcc, 0x0b, 0xa6, 0x53, 0x2e, 0x03, 0xc9, 0xf8, 0x54, 0xe4, 0x30, 0xf7, 0x69, 0xc4, 0xe4,
	0x69, 0x36, 0xec, 0x8f, 0x78, 0xec, 0x45, 0x7c, 0x12, 0x4c, 0xa3, 0x9c, 0x6d, 0x98, 0x8d, 0xbd,
	0x44, 0x9e, 0x27, 0x54, 0x78, 0x92, 0xc5, 0x54, 0xc8, 0x20, 0x4e, 0xca, 0x53, 0x7e, 0x99, 0xfc,
	0xb4, 0xa0, 0x7e, 0x9c, 0x3f, 0x83, 0x5a, 0x50, 0x61, 0x21, 0xb6, 0xba, 0x56, 0xaf, 0xea, 0x57,
	0x58, 0x88, 0xb6, 0xa1, 0x9e, 0x65, 0x2c, 0x1c, 0x9c, 0x1d, 0xe0, 0x4a, 0xd7, 0xea, 0x39, 0xbe,
	0x3d, 0x0b, 0x3f, 0x1e, 0xa0, 0x36, 0xd8, 0x41, 0x92, 0x0c, 0x58, 0x88, 0xab, 0x2a, 0x5f, 0x0b,
	0x92, 0xe4, 0x28, 0x44, 0x5b, 0x50, 0x93, 0x3c, 0x61, 0x23, 0xbc, 0x96, 0x67, 0x55, 0x80, 0x1e,
	0x03, 0x8c, 0x52, 0x1a, 0x48, 0x1a, 0x0e, 0x02, 0x89, 0x6b, 0x5d, 0xab, 0xd7, 0xdc, 0x77, 0xfb,
	0x79, 0x47, 0x7d, 0x53, 0x68, 0xff, 0xc4, 0xd4, 0xe5, 0x3b, 0x1a, 0xfd, 0x5c, 0xa2, 0x87, 0xe0,
	0x24, 0xd9, 0x70, 0xc2, 0xc4, 0x29, 0x15, 0xd8, 0xee, 0x56, 0x7b, 0xcd, 0x7d, 0xdc, 0x37, 0x1a,
	0xbd, 0xcf, 0xbf, 0xf8, 0x54, 0x24, 0x7c, 0x2a, 0xa8, 0x5f, 0x42, 0x49, 0x0a, 0xd7, 0x96, 0xbe,
	0xae, 0xf4, 0xd6, 0x06, 0x3b, 0x16, 0xd1, 0xac, 0x85, 0x8a, 0xca, 0xd5, 0x62, 0x11, 0x1d, 0x85,
	0xe8, 0x11, 0x38, 0x85, 0x42, 0xaa, 0xb9, 0x7f, 0xd4, 0x5a, 0x80, 0xc9, 0x05, 0x6c, 0xbc, 0x54,
	0x85, 0xfb, 0xf4, 0x4b, 0x46, 0x85, 0x9c, 0x57, 0xcf, 0xba, 0x42, 0xbd, 0xca, 0xa5, 0xea, 0x55,
	0xe7, 0xd5, 0x43, 0xb0, 0x16, 0x06, 0x32, 0x50, 0x92, 0xae, 0xfb, 0xea, 0x3c, 0xcb, 0xd1, 0x98,
	0xe5, 0x5a, 0x36, 0x7c, 0x75, 0x26, 0x7f, 0x2c, 0x68, 0x1e, 0xb2, 0x69, 0x68, 0x5e, 0xff, 0x3f,
	0x5e, 0xde, 0x85, 0x75, 0xe3, 0xe5, 0x38, 0xe5, 0xb1, 0xaa, 0xc0, 0xf1, 0x9b, 0x3a, 0x77, 0x98,
	0xf2, 0x18, 0xdd, 0x2e, 0xed, 0x96, 0x1c, 0xdb, 0x0a, 0x60, 0x2c, 0x3d, 0xe1, 0x33, 0xde, 0x09,
	0x9b, 0x15, 0x5f, 0xcf, 0x65, 0x57, 0x01, 0xea, 0x80, 0xcd, 0xc7, 0x63, 0x41, 0x25, 0x6e, 0xa8,
	0xb4, 0x8e, 0xd0, 0x4d, 0x68, 0xf0, 0x34, 0xa4, 0xe9, 0x60, 0x78, 0x8e, 0x1d, 0x45, 0x55, 0x57,
	0xf1, 0x8b, 0x73, 0xf2, 0x0c, 0xd6, 0xdf, 0x32, 0x21, 0x0b, 0x83, 0xef, 0x43, 0x43, 0x4f, 0x86,
	0xc0, 0x96, 0x1a, 0x95, 0xcd, 0x62, 0x54, 0xf4, 0x80, 0xfb, 0x05, 0x82, 0xec, 0x00, 0xbc, 0xa6,
	0xf2, 0x0a, 0xb1, 0xc8, 0x1d, 0xd8, 0x78, 0x45, 0x27, 0xb4, 0xf4, 0x72, 0x19, 0xb0, 0x07, 0x2d,
	0x03, 0xd0, 0xcf, 0x63, 0xa8, 0x8b, 0x6c, 0x34, 0xa2, 0x42, 0x28, 0x58, 0xc3, 0x37, 0x21, 0xb9,
	0x07, 0x6d, 0x3d, 0x8c, 0xa6, 0x8c, 0xcb, 0x49, 0xf7, 0x7f, 0x54, 0xa1, 0xa5, 0x21, 0x1f, 0x68,
	0x7a, 0xc6, 0x46, 0x14, 0xbd, 0x33, 0x43, 0x65, 0x7e, 0xd1, 0x4e, 0xd1, 0xd3, 0xc2, 0xb0, 0xb9,
	0x2b, 0xbd, 0x92, 0xad, 0x6f, 0xbf, 0x7e, 0x7f, 0xaf, 0xb4, 0x88, 0x63, 0x96, 0x8a, 0x78, 0x62,
	0xed, 0xa1, 0x63, 0x68, 0xce, 0x54, 0x33, 0x74, 0x5b, 0xc5, 0xb5, 0xb9, 0xd9, 0x71, 0xdb, 0x45,
	0x76, 0x5e, 0x61, 0x72, 0x5d, 0x31, 0x36, 0x51, 0xc9, 0x88, 0xde, 0x28, 0x19, 0x0d, 0xdb, 0x8d,
	0xe2, 0x5e, 0xa9, 0xed, 0x25, 0x95, 0x75, 0x14, 0xcf, 0x26, 0x6a, 0x15, 0x3c, 0xde, 0x57, 0x16,
	0x5e, 0xa0, 0x4f, 0x46, 0xf5, 0xd5, 0x66, 0x17, 0xdc, 0x70, 0xb7, 0x57, 0xf2, 0xba, 0x42, 0xcd,
	0xbc, 0xb7, 0xcc, 0xfc, 0x19, 0x5a, 0x8b, 0x16, 0xa0, 0xdd, 0xe5, 0x35, 0xb2, 0xe8, 0x8d, 0x7b,
	0xe5, 0x9a, 0x21, 0xbb, 0xea, 0x0d, 0x4c, 0x3a, 0x8b, 0x6f, 0x78, 0x7a, 0xfb, 0x0c, 0x6d, 0xb5,
	0x26, 0x1e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x65, 0x67, 0xd1, 0xda, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	CreateMessage(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Message, error)
	ListMessage(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetMessage(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Message, error)
	DeleteMessage(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) CreateMessage(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/message.MessageService/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ListMessage(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/message.MessageService/ListMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GetMessage(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/message.MessageService/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) DeleteMessage(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/message.MessageService/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/message.MessageService/PublishMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	CreateMessage(context.Context, *CreateRequest) (*Message, error)
	ListMessage(context.Context, *FindRequest) (*ListResponse, error)
	GetMessage(context.Context, *GetRequest) (*Message, error)
	DeleteMessage(context.Context, *DeleteRequest) (*DeleteResponse, error)
	PublishMessage(context.Context, *PublishMessageRequest) (*PublishResponse, error)
}

// UnimplementedMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (*UnimplementedMessageServiceServer) CreateMessage(ctx context.Context, req *CreateRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (*UnimplementedMessageServiceServer) ListMessage(ctx context.Context, req *FindRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessage not implemented")
}
func (*UnimplementedMessageServiceServer) GetMessage(ctx context.Context, req *GetRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (*UnimplementedMessageServiceServer) DeleteMessage(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (*UnimplementedMessageServiceServer) PublishMessage(ctx context.Context, req *PublishMessageRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CreateMessage(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ListMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ListMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/ListMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ListMessage(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetMessage(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).DeleteMessage(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/PublishMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessage",
			Handler:    _MessageService_CreateMessage_Handler,
		},
		{
			MethodName: "ListMessage",
			Handler:    _MessageService_ListMessage_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _MessageService_GetMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _MessageService_DeleteMessage_Handler,
		},
		{
			MethodName: "PublishMessage",
			Handler:    _MessageService_PublishMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/proto/message.proto",
}
